[project]
name = "0629-pre"
version = "0.1.0"
description = "研零预训练内容"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "d2l>=0.17.0",
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.1",
    "numpy>=2.4.6",
    "openai>=3.6.0",
    "opencv-python>=5.0.0.93",
    "tqdm>=4.70.0",
]

[project.optional-dependencies]
cpu = [
    "torch==2.13.0",
    "torchvision==0.28.0",
    "torchaudio==2.11.0",
]

cuda = [
    "torch==2.13.0",
    "torchvision==0.28.0",
]

[tool.uv]
conflicts = [[{ extra = "cpu" }, { extra = "cuda" }]]
required-environments = [
    "sys_platform == 'win32' and platform_machine == 'AMD64'",
]

[tool.uv.sources]
torch = [
    { index = "pytorch-cpu", extra = "cpu" },
    { index = "pytorch-cu132", extra = "cuda" },
]
torchvision = [
    { index = "pytorch-cpu", extra = "cpu" },
    { index = "pytorch-cu132", extra = "cuda" },
]
torchaudio = [{ index = "pytorch-cpu", extra = "cpu" }]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu132"
url = "https://download.pytorch.org/whl/cu132"
explicit = true
