[project]
name = "0629-pre"
version = "0.1.0"
description = "研零预训练内容"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "d2l>=0.17.0",
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.1",
    "numpy>=2.4.6",
    "opencv-python>=5.0.0.93",
]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"

[project.optional-dependencies]
cpu = ["torch", "torchvision", "torchaudio"]

cuda = ["torch", "torchvision", "torchaudio"]

[tool.uv]
conflicts = [[{ extra = "cpu" }, { extra = "cuda" }]]

[tool.uv.sources]
torch = [
    { index = "pytorch-cpu", extra = "cpu" },
    { index = "pytorch-cu132", extra = "cuda" },
]
torchvision = [
    { index = "pytorch-cpu", extra = "cpu" },
    { index = "pytorch-cu132", extra = "cuda" },
]
torchaudio = [
    { index = "pytorch-cpu", extra = "cpu" },
    { index = "pytorch-cu132", extra = "cuda" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu132"
url = "https://download.pytorch.org/whl/cu132"
explicit = true
